(()=>{
  const KEY='reelops_demo_state_v4',SCHEMA=9;
  const now=()=>new Date().toISOString();
  const base={schemaVersion:SCHEMA,project:'Project Aurora',shot:'SHOT 08',creativeVersion:'V2',creativeSubmitted:false,creativeSubmittedAt:null,creativeApproval:false,creativeApprovalAt:null,creativeChangesRequested:false,newCreativeFeedback:0,creativeShared:{brief:true,treatment:true,storyboard:true,reference:true,decisionLog:false},selectedVariant:'B',aiReady:false,aiReadyAt:null,captureComplete:false,packageSent:false,packageSentAt:null,genAsset:false,genAssetAt:null,workingComposite:false,workingCompositeAt:null,v3Submitted:false,v3SubmittedAt:null,v3ChangesRequested:false,v3ChangesAt:null,v4Draft:false,feedbackResolved:0,feedbackResolvedItems:[false,false,false],v4Submitted:false,v4SubmittedAt:null,v4ChangesRequested:false,v4ChangesAt:null,changesRequested:false,approval:false,approvedVersion:null,approvalAt:null,finalMasterReady:false,finalMasterAt:null,deliveryItems:[false,false,false,false],deliverables:0,deliveryRecord:false,deliveryRecordAt:null,delivered:false,archiveRecord:false,archiveAt:null,archived:false,newClientFeedback:0};
  const bool4=v=>{const a=Array.isArray(v)?v.slice(0,4).map(Boolean):[];while(a.length<4)a.push(false);return a};
  const bool3=(v,fallback=0)=>{if(Array.isArray(v)&&v.length===3)return v.map(Boolean);const n=Math.max(0,Math.min(3,Number(fallback)||0));return [0,1,2].map(i=>i<n)};
  function resetVersionAndDelivery(n){n.genAsset=false;n.genAssetAt=null;n.workingComposite=false;n.workingCompositeAt=null;n.v3Submitted=false;n.v3SubmittedAt=null;n.v3ChangesRequested=false;n.v3ChangesAt=null;n.v4Draft=false;n.feedbackResolvedItems=[false,false,false];n.feedbackResolved=0;n.v4Submitted=false;n.v4SubmittedAt=null;n.v4ChangesRequested=false;n.v4ChangesAt=null;n.changesRequested=false;n.approval=false;n.approvedVersion=null;n.approvalAt=null;n.finalMasterReady=false;n.finalMasterAt=null;n.deliveryItems=[false,false,false,false];n.deliverables=0;n.deliveryRecord=false;n.deliveryRecordAt=null;n.delivered=false;n.archiveRecord=false;n.archiveAt=null;n.archived=false}
  function resetDelivery(n){n.finalMasterReady=false;n.finalMasterAt=null;n.deliveryItems=[false,false,false,false];n.deliverables=0;n.deliveryRecord=false;n.deliveryRecordAt=null;n.delivered=false;n.archiveRecord=false;n.archiveAt=null;n.archived=false}
  function enforce(n){
    n.feedbackResolvedItems=bool3(n.feedbackResolvedItems,n.feedbackResolved);n.deliveryItems=bool4(n.deliveryItems);
    if(n.creativeChangesRequested){n.creativeSubmitted=true;n.creativeApproval=false}if(n.creativeSubmitted)n.creativeSubmittedAt=n.creativeSubmittedAt||now();else n.creativeSubmittedAt=null;if(n.creativeApproval){n.creativeSubmitted=true;n.creativeSubmittedAt=n.creativeSubmittedAt||now();n.creativeChangesRequested=false;n.creativeApprovalAt=n.creativeApprovalAt||now()}else if(!n.creativeApproval)n.creativeApprovalAt=null;if(!n.creativeApproval){n.packageSent=false;n.packageSentAt=null;resetVersionAndDelivery(n)}
    if(n.aiReady){n.aiReadyAt=n.aiReadyAt||now();n.captureComplete=true}else n.aiReadyAt=null;
    if(n.packageSent){n.aiReady=true;n.aiReadyAt=n.aiReadyAt||now();n.captureComplete=true;n.packageSentAt=n.packageSentAt||now()}else n.packageSentAt=null;
    if(n.genAsset){n.packageSent=true;n.packageSentAt=n.packageSentAt||now();n.genAssetAt=n.genAssetAt||now()}else n.genAssetAt=null;
    if(n.workingComposite){n.genAsset=true;n.genAssetAt=n.genAssetAt||now();n.workingCompositeAt=n.workingCompositeAt||now()}else n.workingCompositeAt=null;
    if((n.genAsset||n.workingComposite)&&!n.creativeApproval){n.genAsset=false;n.genAssetAt=null;n.workingComposite=false;n.workingCompositeAt=null}if(!n.packageSent){n.genAsset=false;n.genAssetAt=null;n.workingComposite=false;n.workingCompositeAt=null;n.v3Submitted=false;n.v3SubmittedAt=null;n.v3ChangesRequested=false;n.v3ChangesAt=null;n.v4Draft=false;n.v4Submitted=false;n.v4SubmittedAt=null;n.v4ChangesRequested=false;n.v4ChangesAt=null;n.approval=false;n.approvedVersion=null;n.approvalAt=null}
    if(n.v3Submitted){n.workingComposite=true;n.workingCompositeAt=n.workingCompositeAt||now();n.genAsset=true;n.genAssetAt=n.genAssetAt||now();n.packageSent=true;n.packageSentAt=n.packageSentAt||now();n.v3SubmittedAt=n.v3SubmittedAt||now()}if(n.v3ChangesRequested){n.v3Submitted=true;n.v3SubmittedAt=n.v3SubmittedAt||now();n.v3ChangesAt=n.v3ChangesAt||now()}else if(!n.v3Submitted)n.v3ChangesAt=null;if(!n.v3ChangesRequested&&!n.v4ChangesRequested&&!(n.approval&&n.approvedVersion==='V4'))n.feedbackResolvedItems=[false,false,false];n.feedbackResolved=n.feedbackResolvedItems.filter(Boolean).length;
    if(n.v4Draft&&(!n.v3ChangesRequested||n.feedbackResolved<3))n.v4Draft=false;if(n.v4Draft){n.workingComposite=true;n.workingCompositeAt=n.workingCompositeAt||now()}if(n.v4Submitted&&(!n.v4Draft||n.feedbackResolved<3||n.v4ChangesRequested))n.v4Submitted=false;if(n.v4Submitted){n.v4Draft=true;n.v4SubmittedAt=n.v4SubmittedAt||now();n.v4ChangesAt=null}if(n.v4ChangesRequested){n.v4Submitted=false;n.v4ChangesAt=n.v4ChangesAt||now();n.approval=false;n.approvedVersion=null;n.approvalAt=null}else if(!n.v4Submitted)n.v4ChangesAt=null;
    if(n.approval){const version=n.approvedVersion||(n.v4Submitted?'V4':(n.v3Submitted&&!n.v3ChangesRequested?'V3':null)),validV3=version==='V3'&&n.v3Submitted&&!n.v3ChangesRequested,validV4=version==='V4'&&n.v4Submitted&&!n.v4ChangesRequested;if(!validV3&&!validV4){n.approval=false;n.approvedVersion=null;n.approvalAt=null}else{n.approvedVersion=version;n.approvalAt=n.approvalAt||now();n.creativeApproval=true;n.packageSent=true;n.packageSentAt=n.packageSentAt||now();n.genAsset=true;n.genAssetAt=n.genAssetAt||now();n.workingComposite=true;n.workingCompositeAt=n.workingCompositeAt||now();if(version==='V3'){n.v3Submitted=true;n.v3SubmittedAt=n.v3SubmittedAt||now();n.v3ChangesRequested=false;n.v3ChangesAt=null;n.v4Draft=false;n.v4Submitted=false;n.v4SubmittedAt=null;n.v4ChangesRequested=false;n.v4ChangesAt=null;n.feedbackResolvedItems=[false,false,false];n.feedbackResolved=0}else{n.v3Submitted=true;n.v3SubmittedAt=n.v3SubmittedAt||now();n.v3ChangesRequested=true;n.v3ChangesAt=n.v3ChangesAt||now();n.v4Draft=true;n.v4Submitted=true;n.v4SubmittedAt=n.v4SubmittedAt||now();n.v4ChangesRequested=false;n.v4ChangesAt=null;n.feedbackResolvedItems=[true,true,true];n.feedbackResolved=3}}}
    if(!n.approval)n.approvedVersion=null;n.changesRequested=!!(n.v4ChangesRequested||(n.v3ChangesRequested&&!n.v4Submitted&&!n.approval));
    if(!n.approval)resetDelivery(n);if(n.finalMasterReady){if(!n.approval)n.finalMasterReady=false;else n.finalMasterAt=n.finalMasterAt||now()}if(!n.finalMasterReady){n.finalMasterAt=null;n.deliveryItems=[false,false,false,false]}n.deliveryItems=bool4(n.deliveryItems);n.deliverables=n.deliveryItems.filter(Boolean).length;const deliveryReady=!!(n.approval&&n.finalMasterReady&&n.deliveryItems.every(Boolean));if(n.deliveryRecord&&!deliveryReady)n.deliveryRecord=false;if(n.deliveryRecord){n.delivered=true;n.deliveryRecordAt=n.deliveryRecordAt||now()}else{n.delivered=false;n.deliveryRecordAt=null}if(n.archiveRecord&&!n.deliveryRecord)n.archiveRecord=false;if(n.archiveRecord){n.archived=true;n.archiveAt=n.archiveAt||now()}else{n.archived=false;n.archiveAt=null}n.schemaVersion=SCHEMA;return n
  }
  function normalize(saved={}){const n={...base,...saved,creativeShared:{...base.creativeShared,...(saved.creativeShared||{})}};n.feedbackResolvedItems=bool3(saved.feedbackResolvedItems,saved.feedbackResolved);n.deliveryItems=bool4(saved.deliveryItems);if((saved.schemaVersion||0)<7){const hadRevision=!!(saved.v4Draft||saved.v4Submitted||saved.approval||(Number(saved.feedbackResolved)||0)>0);n.v3Submitted=!!(saved.workingComposite||hadRevision);n.v3ChangesRequested=hadRevision;n.v4ChangesRequested=false;n.approvedVersion=saved.approval?'V4':null}if((saved.schemaVersion||0)<8&&saved.approval){n.approvedVersion=saved.approvedVersion||'V4';if(n.approvedVersion==='V4'){n.v3Submitted=true;n.v3ChangesRequested=true;n.feedbackResolvedItems=[true,true,true];n.v4Draft=true;n.v4Submitted=true;n.v4ChangesRequested=false}}if((saved.schemaVersion||0)<9){n.creativeSubmittedAt=saved.creativeSubmittedAt||null;n.aiReadyAt=saved.aiReadyAt||null;n.packageSentAt=saved.packageSentAt||null;n.genAssetAt=saved.genAssetAt||null;n.workingCompositeAt=saved.workingCompositeAt||null;n.v4ChangesAt=saved.v4ChangesAt||null;n.finalMasterAt=saved.finalMasterAt||null}n.finalMasterReady=!!(saved.finalMasterReady||saved.delivered||saved.archived||saved.deliveryRecord||saved.archiveRecord);n.deliveryRecord=!!(saved.deliveryRecord||saved.delivered||saved.archived||saved.archiveRecord);n.archiveRecord=!!(saved.archiveRecord||saved.archived);return enforce(n)}
  function read(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}'),n=normalize(saved);if(saved.schemaVersion!==SCHEMA)localStorage.setItem(KEY,JSON.stringify(n));return n}catch(e){return normalize({})}}
  function write(patch={}){const current=read(),n={...current,...patch,schemaVersion:SCHEMA};if(patch.creativeShared)n.creativeShared={...current.creativeShared,...patch.creativeShared};if(Object.prototype.hasOwnProperty.call(patch,'feedbackResolvedItems'))n.feedbackResolvedItems=[...patch.feedbackResolvedItems];else if(Object.prototype.hasOwnProperty.call(patch,'feedbackResolved'))n.feedbackResolvedItems=bool3(null,patch.feedbackResolved);if(Object.prototype.hasOwnProperty.call(patch,'deliveryItems'))n.deliveryItems=[...patch.deliveryItems];const safe=enforce(n);localStorage.setItem(KEY,JSON.stringify(safe));window.dispatchEvent(new CustomEvent('reelops:state',{detail:safe}));return safe}
  function reset(){const n=normalize({});localStorage.setItem(KEY,JSON.stringify(n));window.dispatchEvent(new CustomEvent('reelops:state',{detail:n}));return n}
  function approvalVersion(s=read()){return s.approval?(s.approvedVersion||'V4'):null}
  function shotLabel(s=read()){if(!s.creativeSubmitted&&!s.creativeApproval)return 'Creative · Internal';if(s.creativeChangesRequested)return `Creative ${s.creativeVersion||'V2'} · Changes`;if(!s.creativeApproval)return `Creative ${s.creativeVersion||'V2'} · In Review`;if(s.approval)return `${approvalVersion(s)} · Approved`;if(s.v4ChangesRequested)return 'V4 · Changes Requested';if(s.v4Submitted)return 'V4 · In Review';if(s.v4Draft)return 'V4 Draft';if(s.v3ChangesRequested)return 'V3 · Changes Requested';if(s.v3Submitted)return 'V3 · In Review';if(s.workingComposite)return 'Working Composite';if(s.genAsset)return 'Selected Asset';if(s.packageSent)return 'AIGC Production';if(s.aiReady)return 'AI Ready';return 'Production Ready'}
  function creativeLabel(s=read()){if(s.creativeApproval)return `Creative Direction ${s.creativeVersion} · Approved`;if(s.creativeChangesRequested)return `Creative Direction ${s.creativeVersion} · Changes Requested`;if(s.creativeSubmitted)return `Creative Direction ${s.creativeVersion} · In Review`;return `Creative Direction ${s.creativeVersion} · Internal Draft`}
  function projectPhase(s=read()){if(s.archiveRecord)return 'Archived';if(s.deliveryRecord)return 'Delivered';if(s.approval)return 'Delivery';if(s.v4Submitted||s.v3Submitted&&!s.v3ChangesRequested)return 'Version Review';if(s.v4ChangesRequested||s.v4Draft||s.v3ChangesRequested||s.workingComposite||s.genAsset)return 'Post-production';if(s.creativeApproval)return 'Production';if(s.creativeSubmitted||s.creativeChangesRequested)return 'Creative Review';return 'Pre-production'}
  function deliveryLabel(s=read()){if(s.archiveRecord)return 'Archived';if(s.deliveryRecord)return 'Delivery Record Complete';if(s.finalMasterReady&&s.deliveryItems.every(Boolean))return 'Ready to Deliver';if(s.finalMasterReady)return `${s.deliverables||0} / 4 Deliverables Ready`;if(s.approval)return `${approvalVersion(s)} Approved · Final Master Pending`;return 'Waiting for Version Approval'}
  function can(action,s=read()){const rules={sendPackage:()=>s.creativeApproval&&s.aiReady,selectAsset:()=>s.packageSent,buildComposite:()=>s.genAsset,submitV3:()=>s.workingComposite&&!s.v3Submitted,requestV3Changes:()=>s.v3Submitted&&!s.v3ChangesRequested&&!s.approval,createV4:()=>s.v3ChangesRequested&&s.feedbackResolved===3&&!s.v4Draft,submitV4:()=>s.v4Draft&&s.feedbackResolved===3&&!s.v4ChangesRequested&&!s.v4Submitted,approveCurrent:()=>s.v4Submitted||s.v3Submitted&&!s.v3ChangesRequested,createFinalMaster:()=>s.approval,completeDelivery:()=>s.approval&&s.finalMasterReady&&s.deliveryItems.every(Boolean),archive:()=>s.deliveryRecord};return rules[action]?!!rules[action]():true}
  window.ReelOpsState={get:read,set:write,reset,shotLabel,creativeLabel,projectPhase,deliveryLabel,approvalVersion,can,key:KEY};
  const style=(attr,href)=>{if(document.querySelector(`link[${attr}]`))return;const e=document.createElement('link');e.rel='stylesheet';e.href=href;e.setAttribute(attr,'1');document.head.appendChild(e)};
  const script=(attr,src)=>{if(document.querySelector(`script[${attr}]`))return;const e=document.createElement('script');e.src=src;e.async=false;e.setAttribute(attr,'1');document.head.appendChild(e)};
  style('data-reelops-polish','polish.css');script('data-reelops-polish','polish.js');style('data-presentation-polish','presentation.css');script('data-presentation-polish','presentation.js');script('data-review-guard','review-guard.js');
  const file=(location.pathname.split('/').pop()||'').toLowerCase();
  if(['live-action.html','generation.html','post.html'].includes(file)){style('data-production-polish','production.css');script('data-production-polish','production.js')}
  if(['post.html','review.html','delivery.html'].includes(file)){style('data-revision-cycle','revision-cycle.css');script('data-revision-cycle','revision-cycle.js')}
  if(['review.html','delivery.html'].includes(file)){style('data-closure-polish','closure-polish.css');script('data-closure-polish','closure-final.js')}
  style('data-nav-semantics','nav-semantics.css');script('data-nav-semantics','nav-semantics.js');style('data-demo-guide','demo-guide.css');script('data-demo-guide','demo-guide.js');style('data-final-pass-style','final-pass.css');script('data-golden-path-qa','golden-path-qa.js');script('data-final-pass-script','final-pass.js');
  if(['project.html','producer.html'].includes(file)){script('data-truth-sync','truth-sync.js');script('data-closure-ux','closure-ux.js')}if(file==='producer.html')script('data-producer-workflow','workflow.js');if(file==='director.html')script('data-director-ux','director-ux.js');
})();